// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dolgozo_Nyilvantartas_Rest_Api;
//
//    var dolgozok = Dolgozok.FromJson(jsonString);

namespace Dolgozo_Nyilvantartas_Rest_Api
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Dolgozok
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("salary")]
        public long Salary { get; set; }

        [JsonProperty("position")]
        public string Position { get; set; }
    }

    public partial class Dolgozok
    {
        public static Dolgozok[] FromJson(string json) => JsonConvert.DeserializeObject<Dolgozok[]>(json, Dolgozo_Nyilvantartas_Rest_Api.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dolgozok[] self) => JsonConvert.SerializeObject(self, Dolgozo_Nyilvantartas_Rest_Api.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
